name: Release

on:
  push:
    tags:
      - "v*"

jobs:
  build-and-release:
    name: Build and Release
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: mobaxterm-keygen
            asset_name: mobaxterm-keygen-linux-amd64
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: mobaxterm-keygen.exe
            asset_name: mobaxterm-keygen-windows-amd64.exe
            
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}
          
      - name: Rust Cache
        uses: Swatinem/rust-cache@v2
          
      - name: Build
        run: cargo build --release --target ${{ matrix.target }}
        
      - name: Prepare asset
        shell: bash
        run: |
          mkdir -p release
          cp target/${{ matrix.target }}/release/${{ matrix.artifact_name }} release/${{ matrix.asset_name }}
          
      - name: Generate changelog
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: release/${{ matrix.asset_name }}
          body: ${{steps.changelog.outputs.changelog}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 